site_name: Entornos Inteligentes
theme:
  name: material
  features:
    - content.code.copy
    - content.tooltips
    - content.footnote.tooltips

nav:
- Summary: 'index.md'
- 3D vision: '3d.md'
- Deep Learning Techniques for Computer vision: 'dnnCV.md'
- Video-based human action/activity recognition: 'HAR.md'
- Image and Video Generation: 'generative.md'

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mdx_math
  - codehilite:
      linenums: false
  - footnotes
  - meta
  - sane_lists
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - bibtex:
      bib_file: "references.bib"

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

  
